package notification;

public enum NotificationType {
	//workspace
	ADD_PROJECT, REMOVE_PROJECT,
	
	//project
	ADD_DOCUMENT, CLOSE_ALL, CLOSE_PROJECT, REMOVE_DOCUMENT, RENAME_PROJECT,
	
	//document
	ADD_PAGE, REMOVE_PAGE, RENAME_DOCUMENT, CLOSE_DOCUMENT,
	
	//page
	RENAME_PAGE,
	
	NEW_PAGE_ELEMENT, REMOVE_PAGE_ELEMENT, SET_DIMENSION,ROTATE,REPAINT;

}
